### PR TITLE
feature: make repository release ready

### LINKED ISSUE #6: Story "Upgrade AAS4J"
# Story "Upgrade AAS4J"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to support the AAS 3.0 specification.

## Acceptance Criteria

- AAS4J that supports AAS 3.0

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770954236_

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

Extends the chart with a mapping domain section and include a portion of the traceability domain as an example.
Stabilize the probes to use the builtin busybox wget and deal with self-signed certificates.
Upgrades some compilation and CICD pipeline dependencies to the latest versions (as suggested by dependabot).
Does some copyright period adjustments.

## WHY

Repository becomes release, integration-test and e2e-test ready. 

## FURTHER NOTES

needs to wait for https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/pull/49 as it puts changes on top. Also adjusts some requirements from there since the source repo went stale.

Closes #6  <-- _insert Issue number if one exists_

### CODE REVIEW

**Review by obalandi — APPROVED** [review]

**Comment by almadigabor** [comment]
Hey @drcgjung, 

- I've opened the IP issue and it can be tracked [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15684)
- The DEPENDENCIES file contains some restricted libraries, I'll open tickets for them then the file needs to be updated.

**Comment by almadigabor** [comment]
Here is the output of the dash-tool run:

```
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-base/5.0.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15685 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-core/5.0.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15686 .
[INFO] A review is required for maven/mavencentral/org.apache.thrift/libthrift/0.19.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15687 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-shacl/5.0.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15688 .
[INFO] A review is required for maven/mavencentral/de.fraunhofer.iosb.ilt.faaast.service/endpoint-opcua/1.0.1.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15689 .
[INFO] A review is required for maven/mavencentral/org.apache.jena/jena-arq/5.0.0.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15690 .
[INFO] A review is required for maven/mavencentral/de.fraunhofer.iosb.ilt.faaast.service/starter/1.0.1.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15691 .
```

**Comment by drcgjung** [comment]
> Hey @drcgjung,
> 
>     * I've opened the IP issue and it can be tracked [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15684)
> 
>     * The DEPENDENCIES file contains some restricted libraries, I'll open tickets for them then the file needs to be updated.

Most of the changes where copyright things. The actual "logic" changes where in the chart. Do we really need an IP check on that?

**Review by almadigabor — COMMENTED** [review]
Let's wait for the IP issue and dependency checks then it looks good from my side.

**Comment by almadigabor** [comment]
Looks like all dependencies have been approved, you can update the DEPENDENCIES file.

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
