### PR TITLE
feat: upgrade faaast for AAS 3.0 support

### LINKED ISSUE #5: Story "Upgrade FAAAST"
# Story "Upgrade FAAAST"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to support the AAS 3.0 specification.

## Acceptance Criteria

- FAAAST release that supports AAS 3.0

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770953080_

### LINKED ISSUE #6: Story "Upgrade AAS4J"
# Story "Upgrade AAS4J"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to support the AAS 3.0 specification.

## Acceptance Criteria

- AAS4J that supports AAS 3.0

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770954236_

### PR DESCRIPTION
**Pull request by drcgjung**
## WHAT

Upgrades faaast service framework from a pre-release 0.1.X to an official release 1.X
As a side-effect switches from (old) admin-shell.io to the (new) eclipse-aas4j AAS model.
Replaces the (now: disabled/removed) AAS4J transformation library with XSLT.
Adapt the configuration and deployment to deal with (now: required) SSL. 

## WHY

This is a feature that is required for a first release (within CX 24.08 milestone).

## FURTHER NOTES

Due to dependency changes, an IP check has to be made on faaast and (recursive) jena deps.

Closes #5
Closes #6

### CODE REVIEW

**Review by bosserf — APPROVED** [review]
great job, well scripted and documented: Thanks Schorsch!

**Review by obalandi — APPROVED** [review]
LGTM!

**Comment by almadigabor** [comment]
I've opened an [IP Issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15462) as the PR contains many changes.

**Comment by drcgjung** [comment]
> IP Issue

I gave the Eclipse IP team a heads up on this ... has been stale for two weeks now.

**Comment by drcgjung** [comment]
> IP Issue

its been approved this morning ;-)

**Comment by almadigabor** [comment]
Hey @drcgjung, Excellent news with the IP ticket! I noticed with some of the modified files that the 2024 modification year is missing from the license headers. Could you please have another look? Thanks!

**Comment by drcgjung** [comment]
> Hey @drcgjung, Excellent news with the IP ticket! I noticed with some of the modified files that the 2024 modification year is missing from the license headers. Could you please have another look? Thanks!

unfortunately the source repo (catenax-ng) has already been frozen. Since I cannot change the source of this PR and do not like to close it for another one, could you please approve/merge this anyway?

The upcoming https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/pull/51 is based on this commit history and I already put in the extended copyright periods ...

**Comment by almadigabor** [comment]
> > Hey @drcgjung, Excellent news with the IP ticket! I noticed with some of the modified files that the 2024 modification year is missing from the license headers. Could you please have another look? Thanks!
> 
> unfortunately the source repo (catenax-ng) has already been frozen. Since I cannot change the source of this PR and do not like to close it for another one, could you please approve/merge this anyway?
> 
> The upcoming #51 is based on this commit history and I already put in the extended copyright periods ...

Sure thing, I merged this one, and the license headers will be fixed in the next PR.

**Pull request merged**
